### ISSUE TITLE
Can not enable external-calendar in Modules administration

### ISSUE THREAD

**Issue by MasterMindNET** [humhub-contrib/external-calendar#10]
I have installed this module in `Administration => Modules => Browse Online`.
After installation, it appears in the `Installed` tab, but when I click enabled, it shows me a pop-up with a message `Enable Module`.

> HumHub Version: 1.5.2; external-calendar Version: 1.1.9; 

Problems:
1. it does not enable this module for me (just in case - other modules can be enabled/disabled, installed; I am running on PHP 7.4; MariaDB 10.3
2. I  believe it needs to be `Enabling Module` instead of `Enable Module`

**Comment by buddh4** [comment]
Any errors in the logs?

**Comment by MasterMindNET** [comment]
I believe we can close it. I had enabled it a month ago. I am on the latest develop branch (humhub) and letest (external_calendar) for 09.19.2020
