### ISSUE TITLE
ReferenceError: clipboard is not defined

### ISSUE THREAD

**Issue by MasterMindNET** [humhub-contrib/external-calendar#15]
Description  
Steps To Reproduce 
1. open you external-caledar
2. make sure you have some events
3. create export
4. click on ` Copy to clipboard` button

Actual Result: clicking on the ` Copy to clipboard` button copies the url
Expected Result: throws the error `ReferenceError: clipboard is not defined`

![image](https://user-images.githubusercontent.com/22347676/88950457-566e7780-d29d-11ea-8c8b-57f94fc0394c.png)
TEXT:

```
humhub.log.js?v=1591265373:149 ERROR - humhub.modules.action: An unexpected error occurred. If this keeps happening, please contact a site administrator. ReferenceError: clipboard is not defined
    at jQuery.fn.init.<anonymous> (humhub.ui.additions.js?v=1591265373:139)
    at ActionBinding.handle (humhub.action.js?v=1596119240:550)
    at HTMLAnchorElement.<anonymous> (humhub.action.js?v=1596119240:802)
    at HTMLDocument.dispatch (jquery.js?v=1596124848:5429)
    at HTMLDocument.elemData.handle (jquery.js?v=1596124848:5233)
```

**Comment by buddh4** [comment]
Cannot recreate this, 

- which HumHub version are you using? 
- Did you try clearing the assets/cache? 
- Are you running in [production or debug mode](https://docs.humhub.org/docs/admin/security#enable-production-mode)
- Please check if there are any network errors when loading

**Comment by MasterMindNET** [comment]
> Cannot recreate this,
> 
> * which HumHub version are you using?
It is 1.6.2. Before (when I posted it), I was runnig 1.5.2
> * Did you try clearing the [assets/cache](https://docs.humhub.org/docs/admin/troubleshooting#clear-cache)?
Yeah, I have just did it, and after that I had a green pop-up (saving that is is succesfully completed)
> * Are you running in [production or debug mode](https://docs.humhub.org/docs/admin/security#enable-production-mode)
I am running the `debug mode` -- `defined('YII_ENV') or define('YII_ENV', 'dev');`
> * Please check if there are any network errors in the network tab of your browser tool
I have got the next errors:
![image](https://user-images.githubusercontent.com/22347676/89710435-afb86400-d98b-11ea-8c04-45beb548d374.png)

**Comment by MasterMindNET** [comment]
It works fine on HumHub develop branch (HumHub  Community Edition Version: 1.7.0-dev)

**Comment by MasterMindNET** [comment]
It works fine on HumHub develop branch (HumHub  Community Edition Version: 1.7.0-dev)
