### ISSUE TITLE
I wish there was a title on the "Export" button, to get the most of the UI

### ISSUE THREAD

**Issue by MasterMindNET** [humhub-contrib/external-calendar#17]
I believe it would be a good idea to add the title to some of the buttons (maybe even not only for this module).
e.g. the "Export" button (the screenshot down below). The icon is good, but if you open it the first time, it may confuse you; you will be unsure about that until you click it.

![image](https://user-images.githubusercontent.com/22347676/89768419-4445d200-db04-11ea-8cdd-2998e56d579f.png)

Thank you!

**Comment by buddh4** [comment]
You mean a tooltip?

**Comment by MasterMindNET** [comment]
> You mean a tooltip?

Yes, exactly.
